AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Step Function Invoker.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/stepfunction-invoker-lambda-1.0-SNAPSHOT.jar
      Handler: com.stepfunction.invoker.StepFunctionHandler
      Runtime: java8
      Description: Java function
      MemorySize: 512
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - AWSStepFunctionsFullAccess
      Tracing: Active