AWSTemplateFormatVersion: '2010-09-09'
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  function:
    Properties:
      CodeUri: s3://stepfunction-lambda-functions/7f1c186ebdfd0d5e338291d531e9fe13
      Description: Java function
      Handler: com.bakdata.aggregate.handler.BankDataAggregationHandler
      MemorySize: 512
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambdaReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      Runtime: java8
      Timeout: 10
      Tracing: Active
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
