
server:
  port: 9093
  
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:ecsdemo}?verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  
  jpa.show-sql: true
        
  flyway:
    enabled: true
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:ecsdemo}?verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    schemas: ${MYSQL_DB}
    user: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    